#allowPublicKeyRetrieval and useSSL settings can't be used in production
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/testdb?allowPublicKeyRetrieval=true&useSSL=false
    username:  root
    password:  2021GreenB@y!

  jpa:
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQL5InnoDBDialect

  # Hibernate ddl auto (create, create-drop, validate, update)
        ddl-auto: update

  # Configure maximum file size

  servlet:
    multipart:  max-file-size=2MB
                max-request-size=2MB
